### ISSUE TITLE
Update with Dotkernel Light

### ISSUE THREAD

**Issue by bidi47** [dotkernel/dotkernel.org#4]
- Migrate project from Dotkernel Frontend to Light
- Edit readme.md - delete everything general, related to dotkernel light, and write something about the project dotkernel.org
- Remove the actions related to qodana, and codecov
- Remove from composer.json PHP 8.2 - will work only on php 8.3

@arhimede, should I write an article about the migration?
It's not much, technically speaking, but it might help as a How-to.

**Comment by arhimede** [comment]
@bidi47 yes, you can write an article about that migration
